### ISSUE TITLE
Introducing ApprovalTask ​​in pipeline, the pipeline cannot find the task

### ISSUE THREAD

**Issue by zijiwork** [openshift-pipelines/manual-approval-gate#169]
Introducing ApprovalTask ​​in pipeline, the pipeline cannot find the task

Pipeline cicd/flask-demo-dev-flow can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "approval": tasks.tekton.dev "approval" not found

k8s version: ```v1.26.15```
tekton version ```v0.40.0```

```
  - name: wait
    taskRef:
      apiVersion: openshift-pipelines.org/v1alpha1
      kind: ApprovalTask
      name: approval
    params:
      - name: approvers
        value:
          - foo
          - bar
          - tekton
      - name: numberOfApprovalsRequired
        value: 2
      - name: description
        value: Approval Task Rocks!!!
```
